### ISSUE TITLE
Problem after update to 2.0.2

### ISSUE THREAD

**Issue by stefagi** [jumping2000/notifier#26]
If I upgrade to version 2.0.2, I get this error:

2020-11-12 19:56:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 338, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 129, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
voluptuous.error.Invalid: must contain at least one of entity_id, area_id.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: must contain at least one of entity_id, area_id.

I also noticed that if the entries I enter in the notification_media_player_google_hub contain spaces in the name (for example
"- Nest Hub
   - Home mini room ")
these are resolved as "media_player.Nest Hub" and obviously don't work.

With version 2.0.1 I have no problems.

Grazie ;)

**Comment by jumping2000** [comment]
If you'are italian, you can write in italian :-)

1) Are there errors in appdaemon log?
2) which is the script that gives the error?

**Comment by stefagi** [comment]
Ok, continuo in italiano e lascio una traccia qui, visto che stiamo affrontando il problema in chat.
Sembra che il problema sia dovuto a come vengono risolti i nomi device Google quando sono inclusi in un gruppo.
Risolvendo il gruppo, invece di prendere il name device, viene preso il friendly_name (che può contenere spazi), accodato a "media_player."
Il risultato è "media_player.home mini cucina" che non è un nome conosciuto.
![image](https://user-images.githubusercontent.com/40425081/99006682-22b11800-2543-11eb-8881-4a07f5f8dd66.png)

**Comment by jumping2000** [comment]
fix published
