### ISSUE TITLE
WARNING AppDaemon: Unable to find module Notifier_Dispatch - initialize() skipped

### ISSUE THREAD

**Issue by rexer78** [jumping2000/notifier#64]
Ciao, ho questo errore da quando ho aggiornato all'ultima versione, da cosa potrebbe dipendere, ho provato a rimuovere tutto compreso il container di appdaemon e il centro notifiche e riscaricare tutto da capo ma continuo ad avere questo errore.

```
2023-07-25 20:57:26.075332 WARNING Notifier_Dispatch: ------------------------------------------------------------
--
 
ModuleNotFoundError: No module named 'packaging'
from packaging import version
File "/conf/apps/notifier/notifier_dispatch.py", line 6, in <module>
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
response = future.result()
File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
modname = await utils.run_in_executor(self, __import__, app_args["module"])
File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 323, in init_object
await self.init_object(app)
File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 1035, in check_app_updates
2023-07-25 20:57:26.075032 WARNING Notifier_Dispatch: Traceback (most recent call last):
2023-07-25 20:57:26.074556 WARNING Notifier_Dispatch: ------------------------------------------------------------
2023-07-25 20:57:26.074286 WARNING Notifier_Dispatch: Unexpected error initializing app: Notifier_Dispatch:
2023-07-25 20:57:26.073948 WARNING Notifier_Dispatch: ------------------------------------------------------------
2023-07-25 20:57:26.038621 WARNING Error: ------------------------------------------------------------


<br class="Apple-interchange-newline">
```

Grazie

**Comment by caiosweet** [comment]
Ciao, nella versione container, mi sa che va aggiunto il modulo "packaging" nella configurazione di appDaemon.
Probabilmente nella sezione python packages.

**Comment by jumping2000** [comment]
"No module named 'packaging' " cioè devi inserire la libreria nel file requirements,txt e riavviare appdaemon

**Comment by rexer78** [comment]
Grazie mille, problema risolto creando il file requirenents.tx nella cartella di appdaemon ed inserrendo la riga packaging, riavviato appdaemon e HA.

Grazie del supporto
